### ISSUE TITLE
Esse módulo está funcional?

### ISSUE THREAD

**Issue by milicofelix** [r-martins/FindCep-M1#1]
Olá Ricardo, tudo bem? Percebi que a última vez q vc mexeu nesse módulo foi há 4 meses atrás, a pergunta é: Ele está funcionando ou vc descontinuou por algum motivo?
Não vejo descrição sobre esse módulo, então acredito que vc só fez alguns testes e não deu mais continuidade.
Agradeço desde já!

**Comment by r-martins** [comment]
Oi @milicofelix.
Está funcionando sim.
Está ativo em www.magenteiro.com inclusive.
Só acho que você precisará pedir uma chave/liberação para seu domínio.

Grande abraço.
